### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException:

### ISSUE THREAD

**Issue by bug-art** [Armen101/AudioRecordView#13]
After using this library I am getting this error and app crashes. But there is no any specific case, it happens rarely. I am using 1.0.2 version. 

Fatal Exception: java.lang.IllegalStateException: View with id 16908290: androidx.appcompat.widget.ContentFrameLayout#onMeasure() did not set the measured dimension by calling setMeasuredDimension()
       at android.view.View.measure(View.java:23209)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
       at android.view.View.measure(View.java:23196)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:23196)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
       at android.view.View.measure(View.java:23196)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:720)
       at android.view.View.measure(View.java:23196)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2802)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1647)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1930)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1535)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7405)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1044)
       at android.view.Choreographer.doCallbacks(Choreographer.java:839)
       at android.view.Choreographer.doFrame(Choreographer.java:774)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1030)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6864)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by Armen101** [comment]
Hi @bug-art, thanks for using AudioRecordView.

It looks weird, I don't think AudioRecordView is directly causing this, I believe that the AudioRecordView crashing is just a symptom of another problem.

If you look online, this exception is not new, and many people have experienced it. I can assume it has something to do with the timer in which you are updating the AudioRecordView, but there could be many other reasons.

Could you provide a test case that reproduces the failure? Without this, there is little I can do.

**Comment by Armen101** [comment]
Also, please use version 1.0.5 because there are some measurement related fixes
